/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Web auth availability + signup posture (no auth required) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Auth status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthStatusResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/github/device/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start the GitHub device flow for the current web user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Device + user codes */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GithubDeviceStartResponse'];
          };
        };
        /** @description Web auth required (X-Archon-User header missing) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Device flow not configured or failed */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/github/device/poll': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Poll the GitHub device flow once for the current web user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['GithubDevicePollBody'];
        };
      };
      responses: {
        /** @description Poll status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GithubDevicePollResponse'];
          };
        };
        /** @description Web auth required (X-Archon-User header missing) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Device flow not configured or failed */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/github': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GitHub connection status for the current web user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Connection status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GithubConnectionStatus'];
          };
        };
        /** @description Web auth required (X-Archon-User header missing) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Disconnect the current web user’s GitHub identity */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Disconnected */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GithubDisconnectResponse'];
          };
        };
        /** @description Web auth required (X-Archon-User header missing) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/providers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the current web user’s connected AI-provider keys */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Connections (metadata only) + connectable provider catalog */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProviderKeyListResponse'];
          };
        };
        /** @description Web auth required (X-Archon-User header missing) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/providers/{provider}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Connect (upsert) an API key for a provider for the current web user */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          provider: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['ProviderKeySetBody'];
        };
      };
      responses: {
        /** @description Key stored (encrypted); response carries no secret value */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProviderKeySetResponse'];
          };
        };
        /** @description Unknown provider or empty key */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Web auth required (X-Archon-User header missing) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Per-user provider keys not enabled on this install */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    post?: never;
    /** Disconnect the current web user’s key for a provider */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          provider: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Disconnected (idempotent) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProviderKeyDeleteResponse'];
          };
        };
        /** @description Web auth required (X-Archon-User header missing) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Per-user provider keys not enabled on this install */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/providers/{provider}/oauth/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Begin a subscription (OAuth) login for the current web user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          provider: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Login session started (mode + URL/user-code) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProviderOAuthStartResponse'];
          };
        };
        /** @description Provider does not support subscription login */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Web auth required (X-Archon-User header missing) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Per-user provider keys not enabled on this install */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description OAuth callback port still held by a previous login attempt — retry shortly */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/providers/{provider}/oauth/poll': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Poll a subscription login session (submit pasted code for manual flows) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          provider: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['ProviderOAuthPollBody'];
        };
      };
      responses: {
        /** @description Poll status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProviderOAuthPollResponse'];
          };
        };
        /** @description Web auth required (X-Archon-User header missing) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Per-user provider keys not enabled on this install */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me/ai-prefs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the current web user’s AI preferences (tiers/aliases/default assistant) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The user’s stored prefs (raw per-user layer, not merged with config) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserAiPrefs'];
          };
        };
        /** @description Web auth required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me/ai-prefs/tiers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update the current web user’s model-tier presets (per-key merge; null unsets) */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateUserTiersBody'];
        };
      };
      responses: {
        /** @description Updated prefs */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserAiPrefs'];
          };
        };
        /** @description Unknown provider or invalid effort */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Web auth required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/auth/me/ai-prefs/aliases': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update the current web user’s @custom aliases (per-key merge; null unsets) */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateUserAliasesBody'];
        };
      };
      responses: {
        /** @description Updated prefs */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserAiPrefs'];
          };
        };
        /** @description Invalid alias name, unknown provider, or invalid effort */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Web auth required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/auth/me/ai-prefs/default': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Set (or clear with null) the current web user’s default assistant + default chat model (written atomically; omitted model clears any pin) */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateUserDefaultBody'];
        };
      };
      responses: {
        /** @description Updated prefs */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserAiPrefs'];
          };
        };
        /** @description Unknown provider */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Web auth required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/conversations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List conversations */
    get: {
      parameters: {
        query?: {
          platform?: string;
          codebaseId?: string;
          mine?: 'true' | 'false';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConversationListResponse'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    /** Create a new conversation */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateConversationBody'];
        };
      };
      responses: {
        /** @description Created conversation */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CreateConversationResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a conversation by platform conversation ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Conversation */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Conversation'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Soft-delete a conversation */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SuccessResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Update a conversation (title) */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateConversationBody'];
        };
      };
      responses: {
        /** @description Updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SuccessResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/conversations/{id}/messages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List message history for a conversation */
    get: {
      parameters: {
        query?: {
          limit?: string;
        };
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Message list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MessageListResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{id}/message': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Send a message (JSON or multipart with file uploads)
     * @description Accepts `application/json` with `{ message: string }` or `multipart/form-data` with a `message` field and optional file attachments (max 5 files, 10 MB each).
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Accepted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DispatchResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/codebases': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List registered codebases */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CodebaseListResponse'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    /** Register a codebase (clone from URL or register local path) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AddCodebaseBody'];
        };
      };
      responses: {
        /** @description Codebase already existed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Codebase'];
          };
        };
        /** @description Codebase created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Codebase'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/codebases/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a codebase by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Codebase */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Codebase'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete a codebase and clean up associated resources */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeleteCodebaseResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/codebases/{id}/env': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List env vars for a codebase */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Env vars for codebase */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CodebaseEnvVarsResponse'];
          };
        };
        /** @description Codebase not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    /** Set (upsert) an env var for a codebase */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['SetEnvVarBody'];
        };
      };
      responses: {
        /** @description Env var set */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['EnvVarMutationResponse'];
          };
        };
        /** @description Codebase not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/codebases/{id}/env/{key}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete an env var from a codebase */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
          key: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Env var deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['EnvVarMutationResponse'];
          };
        };
        /** @description Codebase not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List available workflows */
    get: {
      parameters: {
        query?: {
          cwd?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowListResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/{name}/run': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run a workflow via the orchestrator (JSON or multipart with file uploads)
     * @description Accepts `application/json` with `{ conversationId, message }` or `multipart/form-data` with `conversationId`, `message`, and optional file attachments (max 5 files, 10 MB each).
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Accepted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DispatchResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/dashboard/runs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List enriched workflow runs for the Command Center dashboard */
    get: {
      parameters: {
        query?: {
          status?: string;
          codebaseId?: string;
          search?: string;
          after?: string;
          before?: string;
          limit?: string;
          offset?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DashboardRunsResponse'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs/{runId}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel a workflow run */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Cancelled */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CancelWorkflowRunResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs/{runId}/resume': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resume a failed workflow run (dispatches resume on the parent web conversation) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Resumed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunActionResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs/{runId}/abandon': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Abandon a workflow run (mark as failed) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Abandoned */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunActionResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs/{runId}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve a paused workflow run */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['ApproveWorkflowRunBody'];
        };
      };
      responses: {
        /** @description Approved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunActionResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs/{runId}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reject a paused workflow run */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['RejectWorkflowRunBody'];
        };
      };
      responses: {
        /** @description Rejected */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunActionResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs/{runId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get workflow run details with events */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Workflow run detail */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunDetail'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete a workflow run and its events */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunActionResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/{name}/node-sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Reset persisted per-node provider sessions for a workflow. Optional scope and node filters narrow the deletion. */
    delete: {
      parameters: {
        query?: {
          scope?: string;
          node?: string;
          confirm?: 'all-scopes';
        };
        header?: never;
        path: {
          name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sessions deleted (deleted count may be 0) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ResetWorkflowNodeSessionsResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List workflow runs */
    get: {
      parameters: {
        query?: {
          conversationId?: string;
          status?: string;
          codebaseId?: string;
          limit?: string;
          mine?: 'true' | 'false';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunListResponse'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/runs/by-worker/{platformId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Look up a workflow run by its worker conversation platform ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          platformId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Workflow run */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WorkflowRunByWorkerResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/validate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate a workflow definition without saving */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ValidateWorkflowBody'];
        };
      };
      responses: {
        /** @description Validation result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ValidateWorkflowResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workflows/{name}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch a single workflow definition */
    get: {
      parameters: {
        query?: {
          cwd?: string;
        };
        header?: never;
        path: {
          name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Workflow definition */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GetWorkflowResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    /** Save (create or update) a workflow */
    put: {
      parameters: {
        query?: {
          cwd?: string;
          source?: 'project' | 'global';
        };
        header?: never;
        path: {
          name: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['SaveWorkflowBody'];
        };
      };
      responses: {
        /** @description Saved workflow */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GetWorkflowResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    post?: never;
    /** Delete a user-defined workflow */
    delete: {
      parameters: {
        query?: {
          cwd?: string;
          source?: 'project' | 'global';
        };
        header?: never;
        path: {
          name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeleteWorkflowResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/commands': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List available command names for the workflow node palette */
    get: {
      parameters: {
        query?: {
          cwd?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommandListResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs/{runId}/artifacts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List a run's artifact files
     * @description Walks the run's artifact directory and returns relative file paths with size + mtime. Drives the console Artifacts tab. Returns `{ files: [] }` when the run has no codebase or the codebase name is not in `owner/repo` form.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          runId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ListArtifactsResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get read-only configuration (safe subset) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Configuration */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConfigResponse'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/config/assistants': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update assistant configuration */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateAssistantConfigBody'];
        };
      };
      responses: {
        /** @description Updated configuration */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConfigResponse'];
          };
        };
        /** @description Invalid request body */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/config/tiers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update model-tier presets (small/medium/large)
     * @description Writes the `tiers:` config to ~/.archon/config.yaml. Ungated (works on solo installs). Per-tier merge; a `null` tier value unsets it.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateTiersBody'];
        };
      };
      responses: {
        /** @description Updated configuration */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConfigResponse'];
          };
        };
        /** @description Invalid request body */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/config/aliases': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update @custom model aliases
     * @description Writes the `aliases:` config to ~/.archon/config.yaml. Ungated (works on solo installs). Per-alias merge; a `null` alias value unsets it.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateAliasesBody'];
        };
      };
      responses: {
        /** @description Updated configuration */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ConfigResponse'];
          };
        };
        /** @description Invalid alias name, unknown provider, or invalid effort */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/providers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List registered AI providers */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of registered providers */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProviderListResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/providers/pi/models': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Pi's model catalog (cost/reasoning metadata for the tier picker)
     * @description Best-effort hint surface: returns `{ models: [] }` when the Pi catalog cannot be loaded, never an error — tier/alias saves must not depend on it.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Pi model catalog (metadata only) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PiModelListResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/providers/opencode/credentials': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Introspect OpenCode's backend providers and auth state
     * @description Proxies the embedded OpenCode server's provider introspection (catalog, env var names, install-wide connected state). Heavyweight: starts the embedded server when not already running — call on demand from the settings card, never on passive page load (#1955).
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OpenCode backend providers (metadata only, no secrets) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OpencodeCredentialListResponse'];
          };
        };
        /** @description Embedded OpenCode runtime unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/codebases/{id}/environments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List isolation environments for a codebase */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of isolation environments */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CodebaseEnvironmentsResponse'];
          };
        };
        /** @description Codebase not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Health status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/update-check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Check for available updates */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Update check result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UpdateCheckResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthStatusResponse: {
      enabled: boolean;
      /** @enum {string} */
      signup: 'allowlist' | 'open' | 'disabled';
    };
    GithubDeviceStartResponse: {
      device_code: string;
      user_code: string;
      verification_uri: string;
      interval: number;
      expires_in: number;
    };
    Error: {
      error: string;
    };
    GithubDevicePollResponse: {
      /** @enum {string} */
      status: 'pending' | 'connected' | 'expired' | 'denied' | 'error';
      githubLogin?: string;
      detail?: string;
    };
    GithubDevicePollBody: {
      device_code: string;
    };
    GithubConnectionStatus: {
      connected: boolean;
      githubLogin: string | null;
    };
    GithubDisconnectResponse: {
      success: boolean;
    };
    ProviderKeyListResponse: {
      enabled: boolean;
      connections: components['schemas']['ProviderKeyConnection'][];
      available: string[];
      subscriptionAvailable: string[];
      agents: components['schemas']['AgentCredentials'][];
    };
    ProviderKeyConnection: {
      provider: string;
      /** @enum {string} */
      kind: 'api_key' | 'oauth';
      label: string | null;
    };
    AgentCredentials: {
      id: string;
      displayName: string;
      /** @enum {string} */
      catalog: 'static' | 'dynamic';
      ready: boolean;
      credentials: components['schemas']['AgentCredentialStatus'][];
    };
    AgentCredentialStatus: {
      vendor: string;
      displayName: string;
      kinds: ('api_key' | 'subscription' | 'ambient')[];
      /** @enum {string|null} */
      connected: 'api_key' | 'oauth' | null;
      subscriptionAvailable: boolean;
      installEnv: boolean;
      ambientConfigured?: boolean;
    };
    ProviderKeySetResponse: {
      success: boolean;
      provider: string;
      /** @enum {string} */
      kind: 'api_key';
      label: string | null;
    };
    ProviderKeySetBody: {
      apiKey: string;
      label?: string;
    };
    ProviderKeyDeleteResponse: {
      success: boolean;
    };
    ProviderOAuthStartResponse: {
      sessionId: string;
      /** @enum {string} */
      mode: 'manual' | 'device';
      url?: string;
      userCode?: string;
      verificationUri?: string;
      expiresIn: number;
    };
    ProviderOAuthPollResponse: {
      /** @enum {string} */
      status: 'pending' | 'connected' | 'error';
      detail?: string;
      /** @enum {string} */
      mode?: 'manual' | 'device';
      url?: string;
      userCode?: string;
      verificationUri?: string;
    };
    ProviderOAuthPollBody: {
      sessionId: string;
      code?: string;
    };
    UserAiPrefs: {
      tiers?: components['schemas']['UserTiersConfig'];
      aliases?: {
        [key: string]: components['schemas']['TierEntry'];
      };
      defaultProvider?: string;
      defaultModel?: string;
    };
    UserTiersConfig: {
      small?: components['schemas']['TierEntry'];
      medium?: components['schemas']['TierEntry'];
      large?: components['schemas']['TierEntry'];
    };
    TierEntry: {
      provider: string;
      model: string;
      effort?: string;
      thinking?: unknown;
    };
    UpdateUserTiersBody: {
      tiers: {
        small?: components['schemas']['TierEntry'] & unknown;
        medium?: components['schemas']['TierEntry'] & unknown;
        large?: components['schemas']['TierEntry'] & unknown;
      };
    };
    UpdateUserAliasesBody: {
      aliases: {
        [key: string]: components['schemas']['TierEntry'] & unknown;
      };
    };
    UpdateUserDefaultBody: {
      provider: string | null;
      model?: string | null;
    };
    ConversationListResponse: components['schemas']['Conversation'][];
    Conversation: {
      id: string;
      platform_type: string;
      platform_conversation_id: string;
      codebase_id: string | null;
      cwd: string | null;
      isolation_env_id: string | null;
      ai_assistant_type: string;
      title: string | null;
      hidden: boolean;
      /** Format: date-time */
      deleted_at: string | null;
      /** Format: date-time */
      last_activity_at: string | null;
      user_id: string | null;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    CreateConversationResponse: {
      conversationId: string;
      id: string;
      dispatched?: boolean;
    };
    CreateConversationBody: {
      codebaseId?: string;
      message?: string;
    };
    SuccessResponse: {
      success: boolean;
    };
    UpdateConversationBody: {
      title?: string;
    };
    MessageListResponse: components['schemas']['Message'][];
    Message: {
      id: string;
      conversation_id: string;
      /** @enum {string} */
      role: 'user' | 'assistant';
      content: string;
      metadata: string;
      user_id: string | null;
      /** Format: date-time */
      created_at: string;
    };
    DispatchResponse: {
      accepted: boolean;
      status: string;
    };
    CodebaseListResponse: components['schemas']['Codebase'][];
    Codebase: {
      id: string;
      name: string;
      repository_url: string | null;
      default_cwd: string;
      default_branch: string | null;
      ai_assistant_type: string;
      /** @enum {string} */
      kind: 'repo' | 'folder';
      commands: {
        [key: string]: {
          path: string;
          description: string;
        };
      };
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    AddCodebaseBody: {
      url?: string;
      path?: string;
    };
    DeleteCodebaseResponse: {
      success: boolean;
    };
    CodebaseEnvVarsResponse: {
      keys: string[];
    };
    EnvVarMutationResponse: {
      success: boolean;
    };
    SetEnvVarBody: {
      key: string;
      value: string;
    };
    WorkflowListResponse: {
      workflows: components['schemas']['WorkflowListEntry'][];
      recommended: string[];
      errors?: components['schemas']['WorkflowLoadError'][];
    };
    WorkflowListEntry: {
      workflow: components['schemas']['WorkflowDefinition'];
      source: components['schemas']['WorkflowSource'];
    };
    WorkflowDefinition: {
      name: string;
      description: string;
      provider?: string;
      model?: string;
      /** @enum {string} */
      modelReasoningEffort?: 'minimal' | 'low' | 'medium' | 'high' | 'xhigh';
      /** @enum {string} */
      webSearchMode?: 'disabled' | 'cached' | 'live';
      interactive?: boolean;
      /** @enum {string} */
      effort?: 'low' | 'medium' | 'high' | 'max';
      thinking?:
        | {
            /** @enum {string} */
            type: 'adaptive';
          }
        | {
            /** @enum {string} */
            type: 'enabled';
            budgetTokens?: number;
          }
        | {
            /** @enum {string} */
            type: 'disabled';
          };
      fallbackModel?: string;
      betas?: string[];
      sandbox?: {
        enabled?: boolean;
        autoAllowBashIfSandboxed?: boolean;
        allowUnsandboxedCommands?: boolean;
        network?: {
          allowedDomains?: string[];
          allowManagedDomainsOnly?: boolean;
          allowUnixSockets?: string[];
          allowAllUnixSockets?: boolean;
          allowLocalBinding?: boolean;
          httpProxyPort?: number;
          socksProxyPort?: number;
        };
        filesystem?: {
          allowWrite?: string[];
          denyWrite?: string[];
          denyRead?: string[];
        };
        ignoreViolations?: {
          [key: string]: string[];
        };
        enableWeakerNestedSandbox?: boolean;
        enableWeakerNetworkIsolation?: boolean;
        excludedCommands?: string[];
        ripgrep?: {
          command: string;
          args?: string[];
        };
      } & {
        [key: string]: unknown;
      };
      worktree?: {
        enabled?: boolean;
      };
      mutates_checkout?: boolean;
      persist_sessions?: boolean;
      tags?: string[];
      requires?: 'github'[];
      nodes: components['schemas']['DagNode'][];
    };
    DagNode: {
      id: string;
      depends_on?: string[];
      when?: string;
      /** @enum {string} */
      trigger_rule?: 'all_success' | 'one_success' | 'none_failed_min_one_success' | 'all_done';
      model?: string;
      provider?: string;
      /** @enum {string} */
      context?: 'fresh' | 'shared';
      output_format?: {
        [key: string]: unknown;
      };
      allowed_tools?: string[];
      denied_tools?: string[];
      idle_timeout?: number;
      retry?: {
        max_attempts: number;
        delay_ms?: number;
        /** @enum {string} */
        on_error?: 'transient' | 'all';
      };
      hooks?: {
        PreToolUse?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        PostToolUse?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        PostToolUseFailure?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        Notification?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        UserPromptSubmit?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        SessionStart?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        SessionEnd?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        Stop?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        SubagentStart?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        SubagentStop?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        PreCompact?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        PermissionRequest?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        Setup?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        TeammateIdle?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        TaskCompleted?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        Elicitation?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        ElicitationResult?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        ConfigChange?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        WorktreeCreate?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        WorktreeRemove?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
        InstructionsLoaded?: {
          matcher?: string;
          response: {
            [key: string]: unknown;
          };
          timeout?: number;
        }[];
      };
      mcp?: string;
      skills?: string[];
      agents?: {
        [key: string]: {
          description: string;
          prompt: string;
          model?: string;
          tools?: string[];
          disallowedTools?: string[];
          skills?: string[];
          maxTurns?: number;
        };
      };
      /** @enum {string} */
      effort?: 'low' | 'medium' | 'high' | 'max';
      thinking?:
        | {
            /** @enum {string} */
            type: 'adaptive';
          }
        | {
            /** @enum {string} */
            type: 'enabled';
            budgetTokens?: number;
          }
        | {
            /** @enum {string} */
            type: 'disabled';
          };
      maxBudgetUsd?: number;
      systemPrompt?: string;
      fallbackModel?: string;
      betas?: string[];
      sandbox?: {
        enabled?: boolean;
        autoAllowBashIfSandboxed?: boolean;
        allowUnsandboxedCommands?: boolean;
        network?: {
          allowedDomains?: string[];
          allowManagedDomainsOnly?: boolean;
          allowUnixSockets?: string[];
          allowAllUnixSockets?: boolean;
          allowLocalBinding?: boolean;
          httpProxyPort?: number;
          socksProxyPort?: number;
        };
        filesystem?: {
          allowWrite?: string[];
          denyWrite?: string[];
          denyRead?: string[];
        };
        ignoreViolations?: {
          [key: string]: string[];
        };
        enableWeakerNestedSandbox?: boolean;
        enableWeakerNetworkIsolation?: boolean;
        excludedCommands?: string[];
        ripgrep?: {
          command: string;
          args?: string[];
        };
      } & {
        [key: string]: unknown;
      };
      always_run?: boolean;
      persist_session?: boolean;
      output_type?: string;
      command?: string;
      prompt?: string;
      bash?: string;
      loop?: {
        until: string;
        max_iterations: number;
        /** @default false */
        fresh_context: boolean;
        until_bash?: string;
        interactive?: boolean;
        gate_message?: string;
        prompt: string;
      };
      loop_group?: {
        until: string;
        max_iterations: number;
        /** @default false */
        fresh_context: boolean;
        until_bash?: string;
        interactive?: boolean;
        gate_message?: string;
        nodes: components['schemas']['DagNode'][];
      };
      approval?: {
        message: string;
        capture_response?: boolean;
        on_reject?: {
          prompt: string;
          max_attempts?: number;
        };
      };
      cancel?: string;
      script?: string;
      /** @enum {string} */
      runtime?: 'bun' | 'uv';
      deps?: string[];
      timeout?: number;
    };
    /** @enum {string} */
    WorkflowSource: 'project' | 'bundled' | 'global';
    WorkflowLoadError: {
      filename: string;
      error: string;
      /** @enum {string} */
      errorType: 'read_error' | 'parse_error' | 'validation_error';
    };
    DashboardRunsResponse: {
      runs: components['schemas']['DashboardWorkflowRun'][];
      total: number;
      counts: {
        all: number;
        running: number;
        completed: number;
        failed: number;
        cancelled: number;
        pending: number;
        paused: number;
      };
    };
    DashboardWorkflowRun: {
      id: string;
      workflow_name: string;
      conversation_id: string;
      parent_conversation_id: string | null;
      codebase_id: string | null;
      /** @enum {string} */
      status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | 'paused';
      user_message: string;
      metadata: {
        [key: string]: unknown;
      };
      started_at: string;
      completed_at: string | null;
      last_activity_at: string | null;
      working_path: string | null;
      user_id: string | null;
      codebase_name: string | null;
      platform_type: string | null;
      worker_platform_id: string | null;
      parent_platform_id: string | null;
      current_step_name: string | null;
      total_steps: number | null;
      /** @enum {string|null} */
      current_step_status: 'running' | 'completed' | 'failed' | null;
      agents_completed: number | null;
      agents_failed: number | null;
      agents_total: number | null;
    };
    CancelWorkflowRunResponse: {
      success: boolean;
      message: string;
    };
    WorkflowRunActionResponse: {
      success: boolean;
      message: string;
    };
    ApproveWorkflowRunBody: {
      comment?: string;
    };
    RejectWorkflowRunBody: {
      reason?: string;
    };
    ResetWorkflowNodeSessionsResponse: {
      success: boolean;
      deleted: number;
    };
    WorkflowRunListResponse: {
      runs: components['schemas']['WorkflowRun'][];
    };
    WorkflowRun: {
      id: string;
      workflow_name: string;
      conversation_id: string;
      parent_conversation_id: string | null;
      codebase_id: string | null;
      /** @enum {string} */
      status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | 'paused';
      user_message: string;
      metadata: {
        [key: string]: unknown;
      };
      started_at: string;
      completed_at: string | null;
      last_activity_at: string | null;
      working_path: string | null;
      user_id: string | null;
    };
    WorkflowRunByWorkerResponse: {
      run: components['schemas']['WorkflowRun'];
    };
    WorkflowRunDetail: {
      run: components['schemas']['WorkflowRun'] & {
        worker_platform_id?: string;
        parent_platform_id?: string;
        conversation_platform_id: string | null;
      };
      events: components['schemas']['WorkflowEvent'][];
    };
    WorkflowEvent: {
      id: string;
      workflow_run_id: string;
      event_type: string;
      step_index: number | null;
      step_name: string | null;
      data: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      created_at: string;
    };
    ValidateWorkflowResponse: {
      valid: boolean;
      errors?: string[];
    };
    ValidateWorkflowBody: {
      definition: {
        [key: string]: unknown;
      };
    };
    GetWorkflowResponse: {
      workflow: components['schemas']['WorkflowDefinition'];
      filename: string;
      source: components['schemas']['WorkflowSource'];
    };
    SaveWorkflowBody: {
      definition: {
        [key: string]: unknown;
      };
    };
    DeleteWorkflowResponse: {
      deleted: boolean;
      name: string;
    };
    CommandListResponse: {
      commands: components['schemas']['CommandEntry'][];
    };
    CommandEntry: {
      name: string;
      source: components['schemas']['WorkflowSource'];
    };
    ListArtifactsResponse: {
      files: components['schemas']['ArtifactFile'][];
    };
    ArtifactFile: {
      path: string;
      size: number;
      modifiedAt: string;
    };
    ConfigResponse: {
      config: components['schemas']['SafeConfig'];
      database: string;
    };
    SafeConfig: {
      botName: string;
      assistant: string;
      assistants: {
        [key: string]: components['schemas']['ProviderDefaults'];
      };
      streaming: {
        /** @enum {string} */
        telegram: 'stream' | 'batch';
        /** @enum {string} */
        discord: 'stream' | 'batch';
        /** @enum {string} */
        slack: 'stream' | 'batch';
      };
      concurrency: {
        maxConversations: number;
      };
      defaults: {
        copyDefaults: boolean;
        loadDefaultCommands: boolean;
        loadDefaultWorkflows: boolean;
      };
      tiers?: components['schemas']['TiersConfig'];
      tierDefaults?: components['schemas']['TiersConfig'];
      aliases?: {
        [key: string]: components['schemas']['TierEntry'];
      };
    };
    ProviderDefaults: {
      [key: string]: unknown;
    };
    TiersConfig: {
      small?: components['schemas']['TierEntry'];
      medium?: components['schemas']['TierEntry'];
      large?: components['schemas']['TierEntry'];
    };
    UpdateAssistantConfigBody: {
      assistant?: string;
      assistants?: {
        [key: string]: components['schemas']['ProviderDefaults'];
      };
    };
    UpdateTiersBody: {
      tiers: {
        small?: components['schemas']['TierEntry'] & unknown;
        medium?: components['schemas']['TierEntry'] & unknown;
        large?: components['schemas']['TierEntry'] & unknown;
      };
    };
    UpdateAliasesBody: {
      aliases: {
        [key: string]: components['schemas']['TierEntry'] & unknown;
      };
    };
    ProviderListResponse: {
      providers: components['schemas']['ProviderInfo'][];
    };
    ProviderInfo: {
      id: string;
      displayName: string;
      capabilities: components['schemas']['ProviderCapabilities'];
      builtIn: boolean;
    };
    ProviderCapabilities: {
      sessionResume: boolean;
      mcp: boolean;
      hooks: boolean;
      skills: boolean;
      toolRestrictions: boolean;
      structuredOutput: 'enforced' | 'best-effort' | false;
      envInjection: boolean;
      costControl: boolean;
      effortControl: boolean;
      thinkingControl: boolean;
      fallbackModel: boolean;
      sandbox: boolean;
    };
    PiModelListResponse: {
      models: components['schemas']['PiModelInfo'][];
    };
    PiModelInfo: {
      ref: string;
      provider: string;
      id: string;
      name: string;
      reasoning: boolean;
      cost: {
        input: number;
        output: number;
      };
      contextWindow: number;
    };
    OpencodeCredentialListResponse: {
      providers: components['schemas']['OpencodeCredentialProvider'][];
    };
    OpencodeCredentialProvider: {
      id: string;
      name: string;
      env: string[];
      connected: boolean;
      modelCount: number;
      authMethods: {
        /** @enum {string} */
        type: 'oauth' | 'api';
        label: string;
      }[];
    };
    CodebaseEnvironmentsResponse: {
      environments: components['schemas']['IsolationEnvironment'][];
    };
    IsolationEnvironment: {
      id: string;
      codebase_id: string;
      branch_name: string;
      working_path: string;
      status: string;
      created_at: string;
      updated_at: string;
      days_since_activity: number;
    };
    HealthResponse: {
      status: string;
      adapter: string;
      concurrency: {
        [key: string]: unknown;
      };
      runningWorkflows: number;
      version?: string;
      is_docker: boolean;
      activePlatforms?: string[];
    };
    UpdateCheckResponse: {
      updateAvailable: boolean;
      currentVersion: string;
      latestVersion: string;
      releaseUrl: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
